// Generated by https://quicktype.io

export interface Announcement {
    data: Datum[];
    meta: Meta;
}

export interface Datum {
    id: number;
    attributes: Attributes;
}

export interface Filter {
    filters: {}
}

export interface Attributes {
    title: string;
    createdAt: string;
    updatedAt: string;
    publishedAt: string;
}

export interface Meta {
    pagination: Pagination;
}

export interface Pagination {
    page: number;
    pageSize: number;
    pageCount: number;
    total: number;
}
